cxx_library(
    name = "sum",
    srcs = [ "lib.cpp" ],
    link_style = "static",
)

cxx_binary(
    name = "main",
    srcs = [ "main.cpp" ],
    deps = [ "//:sum" ],
    link_style = "static",
)

cxx_test(
    name = "test",
    use_header_units = True,
    env = {},
    link_style = "static",
    deps = [ "//:sum" , "//gtest:gtest"],
    srcs = ["test.cpp"],
)
